# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e4edabed52867254edfdc00c7a61dd8c018ffbc1e5f5f518d0eb167fd6f22fe91aac7b71fb5ac4d32524720ab78e86046fded938791b54140541d44c48cfe5e3

test:
  secret_key_base: 8775d6f34a124461ad8aada3bd1a132631bb9cac943bfd0160b09d57f558f6694e3cdf839fc66c8de417c8cc801a3b12414708fee7abda4c4db3e51ec0cb6f1b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
